10 scaffold db connector (closes #10)
future-stardust/url-shrtnr-guitarosexuals pull request #23
Opened 2021-03-03 09:49 UTC by yugisu

2021-03-03 10:01 UTC, IINamelessII commented on settings.gradle.kts
> +rootProject.name = "shortener"
:+1:

2021-03-03 10:02 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +import javax.inject.*;
Change to explicit import pls

2021-03-03 10:04 UTC, IINamelessII requested changes
src/main/java/shortener/databaseconnector/DatabaseConnector.java

2021-03-03 10:06 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +import javax.inject.*;
Sry, unusual UI for me, I tried to select the "star" symbol at line 5

2021-03-03 10:09 UTC, IINamelessII requested changes

2021-03-03 10:09 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
unit test?

2021-03-03 10:09 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +import javax.inject.*;
Change to explicit import pls

2021-03-03 10:11 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
(for getInstance)

2021-03-03 10:11 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +import javax.inject.*;
(line 5)

2021-03-03 11:53 UTC, yugisu commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
@IINamelessII I guess there's no need for a test here as the behaviour is pretty straightforward and is kinda a part of the Singleton pattern

2021-03-03 12:22 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
yes, but it still has to be cover by a unit test if we have to have the whole project covered

2021-03-03 12:26 UTC, RedBullDogE approved these changes
I think no test needed for getInstance, so we can merge this branch. Otherwise, suggest your options for testing, @IINamelessII

2021-03-03 12:43 UTC, IINamelessII commented
> I think no test needed for getInstance, so we can merge this branch. Otherwise, suggest your options for testing, @IINamelessII

@RedBullDogE written my option below (in the review's conversation) - regular unit test

2021-03-03 13:19 UTC, IINamelessII requested changes
reopened conversation

2021-03-03 13:31 UTC, IINamelessII commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
discussed

2021-03-03 13:31 UTC, IINamelessII approved these changes

2021-03-03 15:41 UTC, gribozavr commented on src/main/java/shortener/databaseconnector/DatabaseConnector.java
> +  public static DatabaseConnector getInstance() {
Beyonce rule...

2021-03-03 15:59 UTC, AshenNagamaki approved these changes

2021-03-03 18:10 UTC, dvasyab approved these changes

2021-03-03 23:25 UTC, yugisu commented
@IINamelessII @RedBullDogE @dvasyab @AshenNagamaki 
Here are some notes on Repositories:

The idea behind Repositories is to abstract db operations from the controller so data operations could be performed by a single method call (e.g. Repository.findAll()); that way, Controllers should interact with the db through the Repositories layer. 

A Repository should implement a stable API, but under-the-hood realisation can use mocked data until we have database implemented. 

Repositories should be created for every type of introduced record entity (User, Alias, UserAliases, UserSession) - for examples, see the UrlsRepository implemented for Alias entity in the context of this PR.

Repositories are further injected via `@Inject` annotation to the class that needs it  (see /hello ApiController updated in the context of this PR).

**If Repositories mechanism doesn't play well or plain db operations usage would be more optimal and concise, we will be able to get rid of it.**

2021-03-04 11:42 UTC, RedBullDogE requested changes
Need to add throwing exceptions into Repository methods (both in the interface and UrlsRepository implementation) and change tests accordingly

2021-03-04 11:42 UTC, RedBullDogE commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
Should throw NoSuchElementException if the record does not exist

2021-03-04 11:42 UTC, RedBullDogE commented on src/main/java/shortener/database/Repository.java
> +  EntityT insertOne(EntityT record);
Should throw ArgumentException if such record already exists

2021-03-04 11:42 UTC, RedBullDogE commented on src/main/java/shortener/database/Repository.java
> +  EntityT deleteOneByPrimaryKey(PrimaryKeyT pk);
Should throw NoSuchElementException if the record does not exist

2021-03-04 12:45 UTC, IINamelessII requested changes
As you know, naming is almost the hardest things in programming :)
Happily, renames from my comments can be done easily in IDE (it will rework respective client code - places of usage)

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
yes, but simply NotFound
Prefix "Exception" is used for marking non-expected exceptions (for unexpecting behavior)

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT insertOne(EntityT record);
PrimaryKeyViolation

We will not perform a full comparing of records, there is a PK for these purposes

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT deleteOneByPrimaryKey(PrimaryKeyT pk);
NotFound

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/UserAliases.java
> +public record UserAliases(Integer userId, String[] aliases) {
UsersAliases (pay attention to "s" at the end of Users)

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/UserSession.java
> +public record UserSession(Integer userId, String token) {
UsersSession

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
simply get?
Assuming that:
get - selecting a single record
search - selecting multiple records

Then we will be able to not include "One" and "ByPrimaryKey" suffixes, because they will be implied by "get"

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT[] findAll();
search?

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT insertOne(EntityT record);
create?

2021-03-04 12:45 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT deleteOneByPrimaryKey(PrimaryKeyT pk);
simply delete?

since these methods are more about business objects rather than about direct DB "commands"

2021-03-04 12:57 UTC, IINamelessII commented on src/main/java/shortener/database/UserAliases.java
> +public record UserAliases(Integer userId, String[] aliases) {
Due to our discussion in tg - UsersAlias :)

2021-03-04 14:19 UTC, yugisu commented on src/main/java/shortener/database/UserSession.java
> +public record UserSession(Integer userId, String token) {
@IINamelessII Come on :)

2021-03-04 14:23 UTC, yugisu commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
@IINamelessII Actually I propose to use builtin exceptions which do correctly reflect their meaning. I think, these are better than cumbersome custom non-"exceptions".

2021-03-04 14:28 UTC, yugisu commented on src/main/java/shortener/database/Repository.java
> +  EntityT insertOne(EntityT record);
@IINamelessII BTW this would apply only to Alias collection, as I suppose it's better to delegate primary key checks to the DB itself, as well as their assignment (e.g. assignment of id to User).

2021-03-04 14:34 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
Which built-in exceptions do you refer to?

2021-03-04 14:35 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT findOneByPrimaryKey(PrimaryKeyT pk);
@yugisu Which built-in exceptions do you refer to?

2021-03-04 14:40 UTC, IINamelessII commented on src/main/java/shortener/database/Repository.java
> +  EntityT insertOne(EntityT record);
@yugisu This would apply to all tables
by "PK for these purposes" I meant that we will compare by PK, rather than PK will somehow handle it

2021-03-04 14:46 UTC, IINamelessII commented on src/main/java/shortener/database/UserSession.java
> +public record UserSession(Integer userId, String token) {
Please check the design doc with _correct_ naming

Plural form - User's Sessions
Single form - User's Session
(not Users' Session(s) because we have 1 to M here)

' cannot be used in code as part of a name, so it should be just UsersSession for a single form

2021-03-04 14:46 UTC, IINamelessII commented on src/main/java/shortener/database/UserSession.java
> +public record UserSession(Integer userId, String token) {
@yugisu Please check the design doc with correct naming

Plural form - User's Sessions
Single form - User's Session
(not Users' Session(s) because we have 1 to M here)

' cannot be used in code as part of a name, so it should be just UsersSession for a single form

2021-03-04 16:55 UTC, IINamelessII approved these changes

2021-03-04 17:09 UTC, RedBullDogE commented on src/main/java/shortener/urls/UrlsRepository.java
> +  public Alias[] search() {
Maybe it should be named something like `getAll()` according to single `get()`?

2021-03-04 17:11 UTC, IINamelessII commented on src/main/java/shortener/urls/UrlsRepository.java
> +  public Alias[] search() {
@RedBullDogE no

was copied from tg:
get - получить один объект по фк. Либо объект либо ексепшн
search - получить все объекты подпадающие под условия. Коллекция(массив) объектов, не обязательно не пустая

2021-03-04 17:12 UTC, IINamelessII commented on src/main/java/shortener/urls/UrlsRepository.java
> +  public Alias[] search() {
that's different actions from business objects point of view

2021-03-04 17:20 UTC, RedBullDogE commented on src/main/java/shortener/urls/UrlsRepository.java
> +  public Alias[] search() {
In this case, correct the description of the method and add right arguments or overloading

2021-03-04 17:28 UTC, RedBullDogE approved these changes

2021-03-04 17:44 UTC, merged